name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Test, Clippy, Fmt, Checkers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install nightly rustfmt
        run: rustup toolchain install nightly --profile minimal --component rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: cargo test
        run: cargo test

      - name: cargo test (nan-equality)
        run: cargo test --features nan-equality

      - name: cargo clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: rustfmt
        run: ./scripts/fmt --check

      - name: DOC_76 checker
        run: python3 scripts/check_doc_76.py

      - name: RUST_TEST_NAMING checker
        run: python3 scripts/check_test_names.py

  msrv:
    name: MSRV (1.74)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.74.0

      - uses: Swatinem/rust-cache@v2

      - name: cargo check (library)
        run: cargo check --lib --locked

  nightly-constants:
    name: Nightly constants
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly

      - uses: Swatinem/rust-cache@v2

      - name: cargo test (nightly-constants)
        run: cargo test --features nightly-constants
